sonar.organization=gszigethy
sonar.projectKey=gszigethy_HA-LuxevaHeater

sonar.sources=custom_components/luxeva_heater
sonar.tests=tests

sonar.python.version=3.14
sonar.python.coverage.reportPaths=coverage.xml

sonar.exclusions=custom_components/luxeva_heater/translations/**,custom_components/luxeva_heater/brand/**,**/*.png
sonar.cpd.exclusions=tests/**
